### ISSUE TITLE
whats wrong with my code?

### ISSUE THREAD

**Issue by help007** [T-Pham/UILocalNotification-RemotePayload#1]
import UIKit
import CoreData
import UserNotificationsUI
import UserNotifications

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate
{
    var channel = "12"
    var deviceId = ""
    var serverUrl = "http:/dadasda/"
    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool
    {
//        FirebaseApp.configure()
        
        let settings : UIUserNotificationType =  [UIUserNotificationType.alert, UIUserNotificationType.sound]
        UIApplication.shared.registerUserNotificationSettings(UIUserNotificationSettings(types: settings, categories: nil))
        UIApplication.shared.registerForRemoteNotifications()
        
        if UserDefaults.standard.value(forKey: "deviceId") as? String != nil
        {
            deviceId = (UserDefaults.standard.value(forKey: "deviceId") as? String)!
        }
        else
        {
            deviceId = UIDevice.current.identifierForVendor!.uuidString
            UserDefaults.standard.set(deviceId, forKey: "deviceId")
            
            UserDefaults.standard.set(-1, forKey: "categoryIdFilter")
            UserDefaults.standard.set(-1, forKey: "severityRowFilter")
            UserDefaults.standard.set(-1, forKey: "complaintRowFilter")
        }
        
        let signUp = UserDefaults.standard.value(forKey: "signUpFlag") as? String
        
        if signUp == "1"
        {
            self.window = UIWindow(frame: UIScreen.main.bounds)
            
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let initialViewController = storyboard.instantiateViewController(withIdentifier: "HostPageVC")
            self.window?.rootViewController = initialViewController
            self.window?.makeKeyAndVisible()
        }
        return true
    }
    
    func application(_ application: UIApplication, didRegister notificationSettings: UIUserNotificationSettings)
    {
    
    }
//    func application(_ application: UIApplication, handleActionWithIdentifier identifier: String?, forRemoteNotification userInfo: [AnyHashable : Any], withResponseInfo responseInfo: [AnyHashable : Any], completionHandler: @escaping () -> Void)
//    {
//        print("Notification received: \(userInfo)")
//        print("Response Info: \(responseInfo)")
//        
//    
//        completionHandler()
//    }
//    func messaging(_ messaging: Messaging, didRefreshRegistrationToken fcmToken: String)
//    {
//        print("Firebase registration token: \(fcmToken)")
//    }
    
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data)
    {
        let tokenChars = (deviceToken as NSData).bytes.bindMemory(to: CChar.self, capacity: deviceToken.count)
        var tokenString = ""
        
        for i in 0..<deviceToken.count
        {
            tokenString += String(format: "%02.2hhx", arguments: [tokenChars[i]])
        }
        print("deviceToken : ", tokenString)
        
//        Messaging.messaging().apnsToken = deviceToken
        deviceId = tokenString
        UserDefaults.standard.set(tokenString, forKey: "deviceId")
    }
    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error)
    {
        print("Failed to register:", error)
    }
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any])
    {
        print("Notification received: \(userInfo)")
        
        
    }
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void)
    {
         print("NotificatiBackground received: \(userInfo)")
        
        if userInfo["msgtype"] as? String == "2"
        {
            let selectedDate = Date()
            
            let formatter = DateFormatter()
            formatter.dateFormat = "dd/MM/yyyy HH:mm:ss a"
            formatter.amSymbol = "a.m."
            formatter.pmSymbol = "p.m."
            let date = formatter.string(from: selectedDate)
            
            print("date : ", date)
            
            var managedContext : NSManagedObjectContext!
            
            if #available(iOS 10.0, *)
            {
                managedContext = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
            }
            else
            {
                let appDelegate = UIApplication.shared.delegate as! AppDelegate
                managedContext = appDelegate.managedObjectContext
            }
            
            let entity = NSEntityDescription.entity(forEntityName: "PushDetails", in: managedContext)
            let details = NSManagedObject(entity: entity!, insertInto: managedContext)
            
            let aps = userInfo["aps"] as? NSDictionary
            let alert = aps?["alert"] as? NSDictionary
        
            details.setValue(alert?["body"] as? String, forKey: "body")
            
            if alert?["launch-image"] as? String != nil
            {
                details.setValue(alert?["launch-image"] as? String, forKey: "launchImage")
            }
            else
            {
                details.setValue("", forKey: "launchImage")
            }
            details.setValue(userInfo["msgtype"]!, forKey: "msgType")
                        
            if userInfo["ProfilePic"] as? String != nil
            {
                details.setValue(userInfo["ProfilePic"] as? String, forKey: "profilePic")
            }
            else
            {
                details.setValue("", forKey: "profilePic")
            }
            if userInfo["transid"] as? Int != nil
            {
                details.setValue(userInfo["transid"] as? Int, forKey: "transId")
                details.setValue("", forKey: "transIdStr")
            }
            else
            {
                details.setValue(userInfo["transid"] as? Int, forKey: "transId")
                details.setValue(userInfo["transid"] as? String, forKey: "transIdStr")
            }
            details.setValue(date, forKey: "dateTime")
            
            do
            {
                try managedContext.save()
            }
            catch
            {
                print(error)
            }
            
            self.window = UIWindow(frame: UIScreen.main.bounds)
            
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let initialViewController = storyboard.instantiateViewController(withIdentifier: "PushListVC")
            self.window?.rootViewController = initialViewController
            self.window?.makeKeyAndVisible()
        }
        else if userInfo["msgtype"] as? String == "4"
        {
            let selectedDate = Date()
            
            let aps = userInfo["aps"] as? NSDictionary
            let alert = aps?["alert"] as? String
            
            if userInfo["confirmedby"] as? String != nil
            {
                let notification = UILocalNotification()
                notification.fireDate = selectedDate
                notification.alertBody = alert
                notification.soundName = UILocalNotificationDefaultSoundName
                UIApplication.shared.scheduleLocalNotification(notification)
            }
            
            let formatter = DateFormatter()
            formatter.dateFormat = "dd/MM/yyyy HH:mm:ss a"
            formatter.amSymbol = "a.m."
            formatter.pmSymbol = "p.m."
            let date = formatter.string(from: selectedDate)
            
            print("date : ", date)
            
            var managedContext : NSManagedObjectContext!
            
            if #available(iOS 10.0, *)
            {
                managedContext = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
            }
            else
            {
                let appDelegate = UIApplication.shared.delegate as! AppDelegate
                managedContext = appDelegate.managedObjectContext
            }
            
            let entity = NSEntityDescription.entity(forEntityName: "PushDetails", in: managedContext)
            let details = NSManagedObject(entity: entity!, insertInto: managedContext)
            
            
            
            details.setValue(alert, forKey: "body")
            
//            if alert?["launch-image"] as? String != nil
//            {
//                details.setValue(alert?["launch-image"] as? String, forKey: "launchImage")
//            }
//            else
//            {
                details.setValue("", forKey: "launchImage")
//            }
            details.setValue(userInfo["msgtype"]!, forKey: "msgType")
            
            if userInfo["ProfilePic"] as? String != nil
            {
                details.setValue(userInfo["ProfilePic"] as? String, forKey: "profilePic")
            }
            else
            {
                details.setValue("", forKey: "profilePic")
            }
            if userInfo["transid"] as? Int != nil
            {
                details.setValue(userInfo["transid"] as? Int, forKey: "transId")
                details.setValue("", forKey: "transIdStr")
            }
            else
            {
                details.setValue(userInfo["transid"] as? Int, forKey: "transId")
                details.setValue(userInfo["transid"] as? String, forKey: "transIdStr")
            }
            
            details.setValue(date, forKey: "dateTime")
            
            do
            {
                try managedContext.save()
            }
            catch
            {
                print(error)
            }
            
            self.window = UIWindow(frame: UIScreen.main.bounds)
            
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let initialViewController = storyboard.instantiateViewController(withIdentifier: "PushListVC")
            self.window?.rootViewController = initialViewController
            self.window?.makeKeyAndVisible()
        }
    }
    
 
    
    //NotificatiBackground received: [AnyHashable("category"): Ma, AnyHashable("mobile"): 7687687687, AnyHashable("origin"): Chet, AnyHashable("ProfilePic"): , AnyHashable("name"): Sa, AnyHashable("msgtype"): 4, AnyHashable("fla"): 1204, AnyHashable("transid"): 150, AnyHashable("aps"): {
    //alert = "Your ";
    //badge = 1;
    //}]
    
    @available(iOS 10.0, *)
    func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void)
    {
        print("foreground")
        completionHandler(UNNotificationPresentationOptions.alert)
    }
    
    func applicationWillResignActive(_ application: UIApplication)
    {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
    }

    func applicationDidEnterBackground(_ application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }

    func applicationWillEnterForeground(_ application: UIApplication) {
        // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }

    func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
        // Saves changes in the application's managed object context before the application terminates.
        self.saveContext()
    }

    // MARK: - Core Data stack

    lazy var applicationDocumentsDirectory: URL = {
        let urls = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
        return urls[urls.count-1]
    }()
    
    lazy var managedObjectModel: NSManagedObjectModel = {
        let modelURL = Bundle.main.url(forResource: "VM", withExtension: "momd")!
        return NSManagedObjectModel(contentsOf: modelURL)!
    }()
    
    lazy var persistentStoreCoordinator: NSPersistentStoreCoordinator =
        {
            let coordinator = NSPersistentStoreCoordinator(managedObjectModel: self.managedObjectModel)
            let url = self.applicationDocumentsDirectory.appendingPathComponent("VM.sqlite")
            
            do {
                try coordinator.addPersistentStore(ofType: NSSQLiteStoreType, configurationName: nil, at: url, options: nil)
            } catch {
                let dict : [String : Any] = [NSLocalizedDescriptionKey        : "Failed to initialize the application's saved data" as NSString,
                                             NSLocalizedFailureReasonErrorKey : "There was an error creating or loading the application's saved data." as NSString,
                                             NSUnderlyingErrorKey             : error as NSError]
                let wrappedError = NSError(domain: "YOUR_ERROR_DOMAIN", code: 9999, userInfo: dict)
                print("Unresolved error \(wrappedError), \(wrappedError.userInfo)")
                abort()
            }
            
            return coordinator
    }()
    
    
    // MARK: - Core Data stack (iOS 9)
    lazy var managedObjectContext: NSManagedObjectContext = {
        var context: NSManagedObjectContext?
        
        if #available(iOS 10.0, *)
        {
            context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
        }
        else
        {
            let coordinator = self.persistentStoreCoordinator
            var managedObjectContext = NSManagedObjectContext(concurrencyType: .privateQueueConcurrencyType)
            managedObjectContext.persistentStoreCoordinator = coordinator
            return managedObjectContext
        }
        return context!
    }()
    
    // MARK: - Core Data stack (iOS 10)
    @available(iOS 10.0, *)
    lazy var persistentContainer: NSPersistentContainer =
        {
            let container = NSPersistentContainer(name:  "VM")
            container.loadPersistentStores(completionHandler: { (storeDescription, error) in
                if let error = error as NSError? {
                    fatalError("Unresolved error \(error), \(error.userInfo)")
                }
            })
            return container
    }()
    
    // MARK: - Core Data context
    
    lazy var databaseContext : NSManagedObjectContext =
        {
            if #available(iOS 10.0, *)
            {
                return self.persistentContainer.viewContext
            }
            else
            {
                
                return self.managedObjectContext
            }
    }()
    
    // MARK: - Core Data save
    func saveContext ()
    {
        do
        {
            if databaseContext.hasChanges {
                try databaseContext.save()
            }
        } catch {
            let nserror = error as NSError
            
            fatalError("Unresolved error \(nserror), \(nserror.userInfo)")
        }
    }
}

**Comment by T-Pham** [comment]
Hey @help007, your code doesn't seem to use this UILocalNotification extension. Can you make it more clear what problem you are facing with the code?
